# Configuration file for LLMs-Full.txt Generator
# Customize file extensions and other settings here

file_extensions:
  - '.py'
  - '.txt'
  - '.java'
  - '.c'
  - '.cpp'
  - '.h'
  - '.hpp'
  - '.js'
  - '.jsx'
  - '.ts'
  - '.tsx'
  - '.html'
  - '.htm'
  - '.css'
  - '.scss'
  - '.less'
  - '.sh'
  - '.bash'
  - '.go'
  - '.rb'
  - '.php'
  - '.sql'
  - '.xml'
  - '.json'
  - '.yaml'
  - '.yml'
  - '.ini'
  - '.toml'
  - '.md'
  - '.markdown'
  - '.swift'
  - '.kt'
  - '.dart'
  - '.scala'
  - '.groovy'
  - '.perl'
  - '.lua'
  - '.r'
  - '.m'
  - '.asm'
  - '.s'
  - '.f'
  - '.for'
  - '.f90'
  - '.f95'
  - '.f03'
  - '.pas'
  - '.ada'
  - '.v'
  - '.vhdl'
  - '.csproj'
  - '.sln'
  - '.vb'
  - '.vbs'
  - '.pl'
  - '.tcl'
  - '.coffee'
  - '.hs'
  - '.erl'
  - '.rs'
  - '.jl'
  - '.clj'
  - '.lisp'
  - '.scm'
  - '.edn'
  - '.mat'
  - '.m'
  - '.cmake'
  - '.gradle'
  - '.dockerfile'
  - '.gitignore'
  - '.env'
  - '.config'
  - '.tf'
  - '.tfvars'
  - '.proto'
  - '.ps1'
  - '.bat'

# Additional text file extensions for llms generation
text_extensions:
  - '.txt'
  - '.md'
  - '.markdown'
  - '.rst'
  - '.adoc'

# Exclude patterns (supports glob patterns)
exclude_patterns:
  - '*.log'
  - '*__pycache__*'
  - '*.pyc'
  - '.git*'
  - '.DS_Store'

# Output settings
output:
  default_llms_file: 'llms-full.txt'
  default_toc_file: 'toc.md'

# Performance settings
performance:
  max_file_size: 10485760  # 10MB in bytes